### ISSUE TITLE
Consider using a string similarity algorithm: levenshtein to optimize the search experience

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [42bytes-team/wfm-seeker#1]
`(^|.*?\\s·)(inputValue)`
![image](https://github.com/42bytes-team/wfm-seeker/assets/24669431/bc6cf641-c049-4d11-8fe5-e7c8c1da0308)

`(^|.*?\\s·)*(inputValue)`
![image](https://github.com/42bytes-team/wfm-seeker/assets/24669431/b022e03d-8d75-483b-862b-4b1b34872bb1)

https://github.com/42bytes-team/wfm-seeker/blob/e0cc99a5f2cb6a93e094e26a25ccbef3c6f52e6d/src/Seeker.tsx#L304

I'm not sure how it will affect the textNodes in the DropdownInner component
https://github.com/42bytes-team/wfm-seeker/blob/e0cc99a5f2cb6a93e094e26a25ccbef3c6f52e6d/src/Seeker.tsx#L146

**Comment by I-Want-ToBelieve** [comment]
@KycKyc can you tell me where is the items data (field in SeekerProps) in the network request 
```
interface SeekerProps<Item> {
    ...
    items: Item[];
    ...
}
```
![image](https://github.com/42bytes-team/wfm-seeker/assets/24669431/64d44561-391c-4d99-b0cd-d1a2b9d20ec6)

**Comment by lonnstyle** [comment]
> @KycKyc can you tell me where is the items data (field in SeekerProps) in the network request 
> 
> ```
> 
> interface SeekerProps<Item> {
> 
>     ...
> 
>     items: Item[];
> 
>     ...
> 
> }
> 
> ```
> 
> ![image](https://github.com/42bytes-team/wfm-seeker/assets/24669431/64d44561-391c-4d99-b0cd-d1a2b9d20ec6)
> 
> 
> 
> 

@I-Want-ToBelieve I believe you're trying to look for the [items endpoint](https://api.warframe.market/v1/items)

**Comment by KycKyc** [comment]
if you want to feed it with "something" and test results, you can use:
```
type Item = {
    id: string;
    group: string;
    name: string;
};
```

**Comment by lonnstyle** [comment]
adding a `*` or not doesn't affect the result of regex matching, it gives the exact same groups
the regex here is used for splitting user's input and match with item names
e.g. user input `N S`, it will be splitted into `[N,S]`
and `(^|.*?\s)(N)(^|.*?\s)(S)` can also match with `Nekros Prime Set` even without the `*`

thus, I'm going to close this issue, you can open another issue for other suggestions
